<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>Converter.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Converter.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack" Version="2.0.44">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

</Project>
